### ISSUE TITLE
Question about semantic versioning support

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [briandfoy/PPI-App-ppi_version-BDFOY#1]
Hi there,

we used your module in the past to automatically update version numbers in our perl modules before publishing them on CPAN.

Now we switched to semantic release versioning, that is covered by using the version plugin e.g.
```perl
use version 0.9917; our $VERSION = version->declare('v1.12.0');
```

But your tool is not working with that syntax. Is it planned to cover this also in future?

Thanks for letting us know.

Kai

**Comment by briandfoy** [comment]
Sorry this is years later. My Github notifications apparently went into a black hole. I'm not against this feature but I also don't have time to do it myself.

**Comment by briandfoy** [comment]
Note that since you are using recent versions of Perl (not v5.8 or earlier), you don't need to jump through the version hoops.
     
     use v5.10;
     our $VERSION = 'v1.2.3';

In this case, the module works just fine although it did warn about the number format. I've updated the module to allow the option `v` at the beginning.

**Comment by KaiSchwarz-cnic** [comment]
Thanks @briandfoy !
